2104_stackarray: 2104_stackarray.o 2104_stack.o
	gcc -o 2104_stackarray 2104_stackarray.o 2104_stack.o
2104_stackarray.o: 2104_stackarray.c 2104_stack.h
	gcc -c 2104_stackarray.c
2104_stack.o: 2104_stack.c 2104_stack.h
	gcc -c 2104_stack.c