2104_mergesort: 2104_mergesort.o 2104_merge.o
	gcc -o 2104_mergesort 2104_merge.o 2104_mergesort.o
2104_mergesort.o: 2104_mergesort.c 2104_merge.h
	gcc -c 2104_mergesort.c
2104_merge.o: 2104_merge.c 2104_merge.h
	gcc -c 2104_merge.c