2104_dsouzaDesigners: 2104_dsouzaDesigners.o 2104_queue.o
	gcc -o 2104_dsouzaDesigners 2104_queue.o 2104_dsouzaDesigners.o
2104_dsouzaDesigners.o: 2104_dsouzaDesigners.c 2104_queue.h
	gcc -c 2104_dsouzaDesigners.c
2104_queue.o: 2104_queue.c 2104_queue.h
	gcc -c 2104_queue.c